## 09 ``Numpy`` 中arg运算

In [1]:
import numpy as np

In [2]:
x = np.random.normal(0, 1, 1000000)

### 索引

In [4]:
np.min(x)

-5.234981114866857

In [5]:
np.argmin(x)

490149

这个最小值的索引是多少

In [6]:
x[490149]

-5.234981114866857

In [7]:
np.min(x)

-5.234981114866857

In [8]:
np.argmax(x)

45071

In [9]:
x[45071]

5.373618033218932

In [10]:
np.max(x)

5.373618033218932

### 排序和使用索引

In [11]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [12]:
np.random.shuffle(x)
x

array([ 0,  6, 15,  4, 13, 14,  9, 10,  3, 11,  8,  7,  5,  1,  2, 12])

对向量进行乱序操作，shuffle是洗牌操作

In [14]:
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

np.sort 不会改变x，返回被改变的数组。x.sort会对x进行修改

In [17]:
x

array([ 0,  6, 15,  4, 13, 14,  9, 10,  3, 11,  8,  7,  5,  1,  2, 12])

In [18]:
x.sort()

In [19]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [20]:
X = np.random.randint(10, size=(4,4))
X

array([[1, 5, 1, 9],
       [2, 3, 4, 6],
       [8, 6, 8, 0],
       [4, 9, 3, 7]])

In [22]:
np.sort(X)

array([[1, 1, 5, 9],
       [2, 3, 4, 6],
       [0, 6, 8, 8],
       [3, 4, 7, 9]])

默认是把每一行变为有序

In [25]:
np.sort(X, axis=0)

array([[1, 3, 1, 0],
       [2, 5, 3, 6],
       [4, 6, 4, 7],
       [8, 9, 8, 9]])

In [26]:
np.sort(X, axis=1)

array([[1, 1, 5, 9],
       [2, 3, 4, 6],
       [0, 6, 8, 8],
       [3, 4, 7, 9]])

#### 使用索引

In [27]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [28]:
np.random.shuffle(x)

In [29]:
x

array([12, 10, 13,  2,  4,  0,  1, 11,  9,  3,  5,  6, 15,  7,  8, 14])

In [30]:
np.argsort(x)

array([ 5,  6,  3,  9,  4, 10, 11, 13, 14,  8,  1,  7,  0,  2, 15, 12])

最小的数字在数组中索引为5的位置，以此类推

In [31]:
np.partition(x, 3)

array([ 2,  1,  0,  3,  4,  5,  6, 10,  9, 11,  8,  7, 12, 15, 13, 14])

标定点，3前面的数字都比3小，4后面的数字都比3大,但不是有序

In [33]:
np.argpartition(x, 3)

array([ 3,  6,  5,  9,  4, 10, 11,  1,  8,  7, 14, 13,  0, 12,  2, 15])

In [34]:
X

array([[1, 5, 1, 9],
       [2, 3, 4, 6],
       [8, 6, 8, 0],
       [4, 9, 3, 7]])

In [35]:
np.argsort(X, axis=1)

array([[0, 2, 1, 3],
       [0, 1, 2, 3],
       [3, 1, 0, 2],
       [2, 0, 3, 1]])

In [36]:
np.argpartition(X, 2, axis=1)

array([[0, 2, 1, 3],
       [0, 1, 2, 3],
       [3, 1, 2, 0],
       [2, 0, 3, 1]])