## 10 ``Numpy`` 中的比较和Fancy Indexing

### Fancy Indexing

In [1]:
import numpy as np

x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [2]:
x[3]

3

In [3]:
x[3:9]

array([3, 4, 5, 6, 7, 8])

In [4]:
x[3:9:2]

array([3, 5, 7])

In [5]:
[x[3], x[5], x[7]]

[3, 5, 7]

In [8]:
ind = [3, 5, 8]
x[ind]

array([3, 5, 8])

对于向量传入一个索引数组，返回这些索引所对应的值

In [9]:
ind = np.array([[0, 2], [1, 3]])
x[ind]

array([[0, 2],
       [1, 3]])

按照这些索引排列的二维向量

#### Fancy Indexing 应用在二维数组

In [11]:
X = x.reshape(4, -1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [13]:
row = np.array([0, 1, 2])
col = np.array([1, 2, 3])
X[row, col]

array([ 1,  6, 11])

In [14]:
X[0, col]

array([1, 2, 3])

In [15]:
X[:2, col]

array([[1, 2, 3],
       [5, 6, 7]])

In [16]:
col = [True, False, True, True]

In [17]:
X[0, col]

array([0, 2, 3])

### ``numpy.array`` 的比较

In [19]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [20]:
x < 3

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [21]:
x > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [22]:
x <= 3

array([ True,  True,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [23]:
x >= 3

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [24]:
x == 3

array([False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [25]:
x != 3

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [26]:
2 * x == 24 - 4 * x

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False])

In [27]:
X < 6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

### 使用 ``numpy.array`` 的比较结果 

In [36]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [41]:
a = x[x <= 4]
a

array([0, 1, 2, 3, 4])

In [42]:
np.count_nonzero(a)

4

In [44]:
np.sum(x <= 3)

4

In [45]:
np.sum(X % 2 == 0, axis=0)

array([4, 0, 4, 0])

In [46]:
np.sum(X % 2 == 0, axis=1)

array([2, 2, 2, 2])

In [47]:
np.any(x == 0)

True

是否有为0的元素

In [48]:
np.any(x < 0)

False

In [50]:
np.all(x > 0)

False

In [51]:
np.all(x >= 0)

True

In [52]:
np.all(X > 0, axis=1)

array([False,  True,  True,  True])

In [53]:
np.sum((x > 3) & (x < 10))

6

位运算符

In [57]:
np.sum((x > 3) && (x < 10))

SyntaxError: invalid syntax (<ipython-input-57-d834f65999a2>, line 1)

In [58]:
np.sum((x % 2 == 0) | (x > 10))

11

In [59]:
np.sum(~(x == 0))

15

非运算符

### 比较结果和Fancy Indexing

In [60]:
x < 5

array([ True,  True,  True,  True,  True, False, False, False, False,
       False, False, False, False, False, False, False])

In [61]:
x[x < 5]

array([0, 1, 2, 3, 4])

In [62]:
x[x % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [66]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [68]:
X[:,-1]

array([ 3,  7, 11, 15])

In [69]:
X[X[:,-1] % 3 == 0, :]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])

最后一列能被能被3整除，显示全行