## 08 ``Numpy`` 中的聚合操作

### sum

In [1]:
import numpy as np

L = np.random.random(100)
sum(L)

50.93253671796398

In [2]:
np.sum(L)

50.93253671796396

In [4]:
np.random.rand(10)

array([0.96998461, 0.61212078, 0.97904292, 0.0935568 , 0.05764839,
       0.75251588, 0.90787367, 0.64613758, 0.59166365, 0.31995811])

In [5]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

61.5 ms ± 409 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
309 µs ± 4.48 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


### min, max

In [6]:
np.min(big_array)

4.814970061550738e-07

In [7]:
np.max(big_array)

0.9999994355256224

In [8]:
big_array.min()

4.814970061550738e-07

In [9]:
big_array.max()

0.9999994355256224

In [10]:
big_array.sum()

500017.57153864333

### 多维度聚合

In [11]:
X = np.arange(16).reshape(4,-1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [12]:
np.sum(X)

120

In [13]:
np.sum(X, axis=0)

array([24, 28, 32, 36])

沿着第一个维度，行的方向进行计算，得到的是每一列相加的值。

In [14]:
np.sum(X, axis=1)

array([ 6, 22, 38, 54])

注意：axis描述的是将要被压缩的维度。

### 其他聚合操作

In [15]:
np.prod(X)

0

得到所有元素的乘积

In [16]:
np.prod(X + 1)

20922789888000

In [18]:
np.mean(X)

7.5

In [19]:
np.median(X)

7.5

中位数

In [21]:
v = np.array([1, 1, 2, 2, 10])
np.mean(v)

3.2

In [22]:
np.median(v)

2.0

In [19]:
np.percentile(big_array, q=50)

0.50056612640031206

统计学中的50%，百分位

In [23]:
np.median(big_array)

0.5002136723159543

In [24]:
np.percentile(big_array, q=100)

0.9999994355256224

In [25]:
np.max(big_array)

0.9999994355256224

In [26]:
for percent in [0, 25, 50, 75, 100]:
    print(np.percentile(big_array, q=percent))

4.814970061550738e-07
0.25011526599692036
0.5002136723159543
0.7498445756767711
0.9999994355256224


In [24]:
np.var(big_array)

0.083379660489048227

var 求方差

In [27]:
np.std(big_array)

0.28861891343522755

std 求标准差

In [29]:
x = np.random.normal(0, 1, 1000000)

均值为0，标准差为1

In [32]:
np.mean(x)

-0.0010743500428363143

In [33]:
np.std(x)

0.9998847247260462