## 04 创建 ``numpy.array``

In [1]:
import numpy as np

### ``numpy.array``

In [2]:
nparr = np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 其他创建 ``numpy.array`` 的方法

#### ``zeros``

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.zeros(10, dtype=float)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
np.zeros(shape=(3, 5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

#### ones

In [7]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

#### full

In [9]:
np.full((3, 5), 666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

In [10]:
np.full(fill_value=666, shape=(3, 5))

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

#### arange

In [13]:
[i for i in range(0, 20, 2)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [14]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
[i for i in range(0, 1, 0.2)]

TypeError: 'float' object cannot be interpreted as an integer

python中的Array不能传入浮点数，但是np.arange是可以的

In [17]:
np.arange(0, 1, 0.2)

array([0. , 0.2, 0.4, 0.6, 0.8])

In [18]:
[i for i in range(0, 10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [19]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
[i for i in range(10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [21]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### linspace

0-20里取十个点，包括0 20的

In [22]:
np.linspace(0, 20, 10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [23]:
np.linspace(0, 20, 11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [24]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

#### random

##### randint

In [28]:
np.random.randint(0, 10)    # [0, 10)之间的随机数

4

In [29]:
np.random.randint(0, 10, 10)

array([2, 5, 1, 5, 3, 9, 7, 2, 2, 9])

In [30]:
np.random.randint(0, 1, 10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [31]:
np.random.randint(0, 10, size=10)

array([9, 4, 9, 9, 9, 6, 4, 2, 8, 1])

In [32]:
np.random.randint(0, 10, size=(3,5))

array([[4, 5, 5, 6, 9],
       [7, 0, 0, 4, 8],
       [5, 7, 2, 2, 7]])

In [33]:
np.random.randint(10, size=(3,5))

array([[4, 7, 2, 9, 9],
       [3, 8, 5, 0, 1],
       [0, 1, 6, 6, 9]])

##### seed

In [37]:
np.random.seed(666)

In [38]:
np.random.randint(0, 10, size=(3, 5))

array([[2, 6, 9, 4, 3],
       [1, 0, 8, 7, 5],
       [2, 5, 5, 4, 8]])

In [39]:
np.random.seed(666)
np.random.randint(0, 10, size=(3,5))

array([[2, 6, 9, 4, 3],
       [1, 0, 8, 7, 5],
       [2, 5, 5, 4, 8]])

##### random

0-1均匀分布之间的浮点数

In [45]:
np.random.random()

0.956191512597935

In [46]:
np.random.random((3,5))

array([[0.73353358, 0.71210247, 0.2427146 , 0.57043673, 0.57773404],
       [0.89274848, 0.12138544, 0.66083873, 0.16459271, 0.09435837],
       [0.5876144 , 0.86014445, 0.82936987, 0.65091808, 0.51832728]])

##### normal

正态分布的随机数，均值为0，方差为

In [47]:
np.random.normal()

1.4202491357304665

In [50]:
np.random.normal(10, 100)

63.40150279992497

In [51]:
np.random.normal(0, 1, (3, 5))

array([[-1.19574802, -0.28915737, -0.24332703, -0.74266653,  1.20790511],
       [ 1.02787711,  0.0573882 , -1.56003976, -0.30401161, -1.19843592],
       [-0.87183499,  0.17659718, -0.20263364,  0.96702908, -1.93169617]])

`np.random.<TAB>` 查看random中的更多方法

In [52]:
np.random?

In [42]:
np.random.normal?

In [40]:
help(np.random.normal)

Help on built-in function normal:

normal(...) method of mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution.
    scale : float or array_like of floats
        Standard deviation (spread or "width") of the distribution.
    size : int or tuple of ints, optional
        Output shap